atom/find-and-replace

- lib/project/results-model.coffee
- spec/project-find-view-spec.coffee
:warning: Depends on atom/atom@bdfc862dac5905989f2c5b71fe8744476d540f17 being released :warning:
> Call atom.workspace.scan and .replace instead of atom.project.scan and .replace

- lib/project/helpers.coffee
- lib/project/result-view.coffee
- spec/results-view-spec.coffee
This way, when there are multiple project paths (say `atom` and `find-and-replace`), you'll see paths like `atom/spec/spec-helper.coffee` and `find-and-replace/package.json`, so you can tell which root directory each path belongs to.
> Disambiguate relative paths in project results view

- styles/find-and-replace.less
The changes that I brought to the LESS stylesheet aim to fix the issue mentioned in #358.
Line-wrapping fix|Overflow fix
-----------------------|----------------
Oh, and that also prevents the `.find-meta-container` from overflowing and blocking interaction with the search field.
> Prevent search field from collapsing when layout space is insufficient

- lib/find-view.coffee
- lib/project-find-view.coffee
- styles/find-and-replace.less
This is a continuation of PR #359.
If the width gets too narrow, the mini editors wrap to a new row and the buttons stretch full width. Not that likely people use it that narrow, but still looks less broken.
Before:
After:
> Wrap UI on narrow width

- lib/find-view.coffee
- lib/project-find-view.coffee
- styles/find-and-replace.less
This PR replaces the text icons with SVG versions. Closes #370
Before:
After:
Not sure about adding the SVG inside the find-view: https://github.com/atom/find-and-replace/blob/19b742461795b0a19c03ff8ce076f0f2249c6c03/lib/find-view.coffee#L46-L76 It needs to be inline so that the icon color changes based on the text color. But would be better if it can stay an external file. Does space pen have some way to do an "include" instead of `@raw`? Like:
```coffee
@include 'atom://find-and-replace/assets/icons.svg'
```
> Replace icons 

- styles/find-and-replace.less
There seems to be an always present scrollbar at the bottom of the panel, you can see it here on two different themes (atom-dark-ui and outlander-ui):
Its still there on other themes like one-dark, however it is hard to see since the `::--webkit
-scrollbar-track` has the same background-color as it's container. Here is what it looks like with this change: 
The scrollbar still appears when the content reaches the `@min-width: 200px`, so that part will still work. 
This is all assuming that we don't want to want to always show the scrollbar track. If `overflow-x` was set to `scroll` intentionally for this reason, than I suppose this change can be disregarded. However, I would say that it looks much better this way. 
Thanks, and let me know if I missed anything!
Note: Reproduced/Tested on …
> Only show scrollbar when there is overflow

- lib/find-view.coffee
There are currently tooltips for all buttons in the find view except the "whole word" option button. This PR adds the tooltip to that button to match the others in that view.
> Add tooltip to whole word button

- lib/project-find-view.coffee
Fixes a bug that caused exception to be thrown if you used the `Search in Directory` context menu command from the tree-view after already performing a project search.
> Fix accidental reassignment of path var

- keymaps/find-and-replace.cson
- lib/find-view.coffee
- lib/project-find-view.coffee
- package.json
- spec/find-view-spec.coffee
- spec/project-find-view-spec.coffee
Add ability to search for the next and previous occurrence of the
current selection or the word containing the cursor in the absence
of a selection. This behaviour, and associated keybindings, is
identical to that of Sublime Text and Visual Studio, among others.
This change also makes the use-selection-as-find-pattern
command use the word containing the cursor in the absence of a
selection instead of simply clearing the existing search pattern, so
that the behaviour is consistent (and code can be reused internally).
This change implements the enhancement described in issue #210.
> Implement find-next/previous-selected functionality

- lib/buffer-search.coffee
- lib/find-view.coffee
- lib/find.coffee
- lib/project-find-view.coffee
- spec/buffer-search-spec.coffee
:warning: Depends on Atom features that won't be released until 0.202 :warning:
Currently, whenever a buffer stops changing, we re-scan the entire buffer for strings matching our search. This can take a long time and can delay the UI responding to typing.
Here's a flame graph taken while typing in the middle of jQuery 2.0.3 (88,000) lines while searching for the string `e` (20769 results). Rescanning took **681 ms**.
This new approach is to keep track of the buffer changes that occur between scans, and only rescan the changed regions.
Here's a flame graph for the same operation as above. Rescanning took **8 ms**.
This uses a new (and for the time being, undocumented) feature of `text-buffer`: the `Patch` class that allows text changes to be aggregated and grouped (see …
> Re-scan only changed region when buffer changes

- lib/project-find-view.coffee
- spec/project-find-view-spec.coffee
Prevent duplicate "Project Find Results" panels. Closes #378
> Prevent duplicate "Project Find Results" panels

- lib/find-view.coffee
- spec/find-view-spec.coffee
This fixes https://github.com/atom/find-and-replace/issues/402#issuecomment-118548573 and closes https://github.com/atom/find-and-replace/issues/402 (since the initial report was fixed in ed00ffb, I believe):
* 466c592 adds a [failing spec](https://travis-ci.org/atom/find-and-replace/builds/69598472) to demonstrate the problem
* a519074 [fixes the problem](https://travis-ci.org/atom/find-and-replace/builds/69598769) by checking that `@markers` is defined before calling `.length` on it.
cc @kevinsawicki @benogle for :eyes:
> Don’t throw exception when replacing with an empty find string

- lib/find-view.coffee
- lib/find.coffee
- spec/find-view-spec.coffee
The idea of this pull request is to scroll the editor window on the result when you type, without having to press enter.
> Scroll to first result on type

- keymaps/find-and-replace.cson
- lib/project-find-view.coffee
- lib/project/results-model.coffee
- spec/project-find-view-spec.coffee
- styles/find-and-replace.less
This PR closes https://github.com/atom/find-and-replace/issues/339 .
Tests were heavily inspired by the "case sensitivity" tests.
Looking forward to your feedback.
> Add whole word option for project find

- lib/find-view.coffee
- lib/project-find-view.coffee
- lib/project/util.coffee
- spec/find-view-spec.coffee
- spec/project-find-view-spec.coffee
Currently, if the Regex option is enabled and the use-selection-as-find-pattern command is triggered on a string like `function foo($bar) {`, then the find-window's search string won't actually match the selection since the characters in the string don't make for a valid regular expression.
If the Regex option is selected, then the selection string should be escaped so that it is a valid regular expression.
This patch escapes the search string when the regex option is enabled, allowing the resulting pattern to match the selection.
Closes #455
> Escape search on use-selection-as-find-pattern and Regex enabled #455

- lib/find-view.coffee
- lib/find.coffee
- spec/find-view-spec.coffee
This is intended to assuage the editor freezing when live (auto) searching in buffer until we get to really truly fixing #145. I've set the default minimum character length to 3.
Closes #174 
Closes #440 
Closes #368 
Closes #153
> Add a `liveSearchMinimumCharacters` setting

- lib/project-find-view.coffee
- lib/project/results-model.coffee
- spec/project-find-view-spec.coffee
This is a tuneup for https://github.com/atom/find-and-replace/issues/331. People are hosing their working state and it sucks. Replace all was a little too eager. This PR changes a few things
First, you must have run a search with results to enable the replace all functionality. Before a search or after a search with no results, the replace-all function is disabled, and the command will 'beep':
The second thing is a confirm box on replace all:
And the third is that it will not replace unless the search pattern is the same as the results pattern. Previously, if you searched for `welcome`, changed the find box to `something`, then ran a replace all, it would first search for `something`, then do the replace all on `something`. Now you must explicitly search for the string before you can …
> Update project replace-all flow 

- lib/find.coffee
- spec/find-view-spec.coffee
Currently there is no way to focus the editor when focused in find panel, other than closing the find panel with escape. This PR binds `window:focus-next-pane` to focus the editor, so you can use the same keybinding you use to move focus between panes.
This coupled with https://github.com/atom/atom/pull/8220 should up the keybinding game when focused in the find panel.
> Focus the editor when window:focus-next-pane is triggered

- lib/buffer-search.coffee
- lib/find-options.coffee
- lib/find-view.coffee
- lib/find.coffee
- lib/project-find-view.coffee
- lib/project/match-view.coffee
- lib/project/results-model.coffee
- lib/project/results-pane.coffee
- lib/project/util.coffee
- package.json
- spec/buffer-search-spec.coffee
- spec/project-find-view-spec.coffee
- spec/results-model-spec.coffee
This introduces a `FindOptions` object containing the current state of the options like `useRegex`, and the pattern values. Both models share this `FindOptions` object. 
This also has refactoring to make both views use their models and the `FindOptions` in a consistent way. Hopefully the code is a lot more straightforward.
This is what it looks like (toggling in project find, affecting buffer find):
Closes #431 
Closes #432
> Share settings between find-view and project-find-view

- lib/find-view.coffee
- lib/project-find-view.coffee
- spec/find-view-spec.coffee
- spec/project-find-view-spec.coffee
- styles/find-and-replace.less
This PR implements syntax highlighting for regular expression searches and will fix #458.
Highlighting works in both the buffer-find and project find dialogs and defaults to text colors that are required by all themes. Themes can override the styling to tweak colors as they desire.
> Regex syntax highlighting

- lib/find.coffee
- lib/project/util.coffee
- lib/select-next.coffee
- spec/select-next-spec.coffee
Currently when using `cmd-d`, we're checking if the selected text is a word, if so, we only select words, and skip matches within other words. Tons of people think this is a bug.
Someone else's gif: 
This PR retains the current behavior when the `wholeWord` option is enabled in one of the find panels, and will match all the things when `wholeWord` is false.
Closes atom/atom#6800
Closes #476
Closes #340
Closes #430
Closes #356
Closes #450
> Use wholeWord option in select-next (cmd-d)

- lib/project/results-model.coffee
- lib/project/results-view.coffee
- package.json
- spec/results-view-spec.coffee
Inspired by @muan's #320, this adds sorting to the project find results. I'm sorting them as they come into the model, rather than the view as in #320.
Closes #64 
Closes #320
> Sort project find results

- lib/project/match-view.coffee
- spec/results-view-spec.coffee
Previously, it always tried to open the item in the left pane. Now, it only opens in the left pane when `openProjectFindResultsInRightPane` is true.
Closes #484
> MatchView core:confirm only opens on left when openOnRight is true

- lib/buffer-search.coffee
- spec/find-view-spec.coffee
Basically, when there is an empty selection, it ignores the option.
Closes #470
Closes #228
Closes #173
> Search whole buffer when no selection and in current selection toggled

- styles/find-and-replace.less
Fixes #406.
/cc: @benogle @izuzak
> Force search results outlines to be in front of other highlights

- lib/find-view.coffee
- lib/project-find-view.coffee
- spec/find-view-spec.coffee
- spec/project-find-view-spec.coffee
- styles/find-and-replace.less
This pull request adds syntax-highlighting for regular expression replacement strings, first mentioned in #458 as a companion to syntax-highlighting for the regular expression search strings themselves.
Note that this is dependent on a new [source.js.regexp.replacement grammar](https://github.com/adamfranco/language-javascript/blob/regexp_replacement_grammar/grammars/regular%20expression%20replacement%20%28javascript%29.cson) provided in [adamfranco/language-javascript/regexp_replacement_grammar](https://github.com/adamfranco/language-javascript/tree/regexp_replacement_grammar). I'll link to the pull request for that code once it has been submitted.
> Add regexp replacement highlighting

- lib/project/results-view.coffee
- spec/project-find-view-spec.coffee
- spec/results-view-spec.coffee
This turned into kind of a rabbit hole. My intent was to fix move-to-bottom and add move-to-top. 
Changes:
* Fixes `core:move-to-bottom` to actually work
* Adds `core:move-to-top` support
* Adds `core:page-down` support
* Adds `core:page-up` support
* Allow selecting paths even when they are not collapsed
* Fixes movement when files have been updated. Updating a file so it no longer has matches for the search string removes old results from the `ResultsView` by hiding the `ResultView` element for the path. Previously, it would attempt to select these invisible elements, which would make the selection 'stick' in the removed element location when arrowing through the results.
> Improve keyboard movement in project results pane

- lib/select-next.coffee
- spec/select-next-spec.coffee
Address https://github.com/atom/atom/issues/9003
This was a fun one liner... until it was time to write some specs - there's tons of options permutations !
Ultimately the various cases will use one of 2 regex with 2 flag options for each, so that is 4 tests.
( Note that 2 of those 4 cases are the normal/current behavior so there would be no harm removing them. )
Case sensitive was the default everywhere before this PR, so I explicitly set it to true on other tests to keep things as they where.
> Use findOptions.caseSensitive when selecting next occurrence (cmd-d)

- lib/find.coffee
- lib/project-find-view.coffee
- spec/project-find-view-spec.coffee
To have the same behaviour as Sublime, if I enable this option the find panel is closed when the search is finished.
> Add an option to close the find panel after search

- lib/project-find-view.coffee
- styles/find-and-replace.less
This is to create a 'Find' button so that users are able to press Find instead of having to press enter.
This is to improve user friendiness, instead of having to guess enter = find.
This is my first dabble in coffee, code review appreciated. 
Please see https://github.com/atom/find-and-replace/issues/297
Cheers,
----
Added by @simurai
Before:
After:
Once this gets merged, also merge One dark/light PRs https://github.com/atom/one-dark-ui/issues/91 + https://github.com/atom/one-light-ui/issues/35.
> Project View Search Button

- lib/find-view.coffee
- lib/project-find-view.coffee
- lib/project/results-model.coffee
- spec/find-view-spec.coffee
- spec/project-find-view-spec.coffee
Basically, this adds a tooltip when the replace buttons are disabled. 
Previously, we were using the `disabled` attribute / prop on the buttons. This doesnt play well with the tooltips, which led to #501. This PR changes the buttons to use a `disabled` CSS class, which looks disabled, but gives us control. There are already guards in place to not allow replacing when no results resulting in a 'beep' (OS X bonk), so clicking a 'disabled' button will just 'beep'.
cc @atom/feedback if you have phrasing ideas on the disabled tooltip, that would be nice.
Fixes #530 
Fixes #501 
Fixes #504 
Fixes #537
> Fix disabled replace buttons and their tooltips

- lib/find.coffee
Not sure if it's just a copy/paste issue but I think it should serialize the `pathsHistory` and not the `replaceHistory`.
Initially reported on discuss: https://discuss.atom.io/t/remember-search-filter/21437
> Fix wrong history serialized for paths

- spec/results-view-spec.coffee
The spec changed in this PR seems to be the only failure (at least locally) for https://github.com/atom/atom/pull/8968. I couldn't backtrack the reason why this started to fail, but there seems to be a super slender change in the height of displayed items.
Manually logging out the `.selected` items revealed that, e.g. instead of `215`, item `216` gets selected: this might be related to the test runner stylesheets setup, but it seems quite negligible given that we haven't changed any line of production code in this package. As a result, I changed the spec so that it doesn't rely on _static_ numbers anymore: other than telling a better story, I think this increases its resiliency as well.
I'd :heart: to have some feedback on this before merging it.
/cc: @nathansobo @maxbrunsfeld
> Increase spec resiliency by not relying on actual numbers

- lib/buffer-search.coffee
- spec/buffer-search-spec.coffee
This reverts commit 9082bc451acf2004696ea3db236918ba2e90e516.
Fixes https://github.com/atom/find-and-replace/issues/497
> Revert "Ignore 0 length matches"

- lib/find-view.coffee
- spec/find-view-spec.coffee
- styles/find-and-replace.less
Flashes an arrow indicator for one second when find wraps around. This helps the user quickly see if he/she has reached the bottom or top. Also found in XCode, Eclipse, Mac Terminal, BBEdit, etc.
> Show wrap around icon when searching (close #401)

- lib/find.coffee
- lib/select-next.coffee
- spec/select-next-spec.coffee
This PR fixes #521 and reverts #482 and #541.
`find-and-replace:select-next` has two core functions.  When nothing is selected, it performs the **SelectWord** function and selects the word(s) under the cursor(s).  When a selection exists, it performs the **SelectNext** function and selects the next occurrence of the selected text.
As discussed in #521, this PR changes the behavior of **SelectNext** depending on whether the existing selection was made using **SelectWord**.
- If the existing selection was made using **SelectWord**, then following **SelectNext** actions will match only whole words.
- If the existing selection was made any other way (e.g. mouse, shift + arrow keys, find panel), then following **SelectNext** actions will match any occurrence.
Since …
> Disconnect SelectNext from findOptions and vary behavior based on initial selection.

- lib/find-view.coffee
- styles/find-and-replace.less
This is an extension on https://github.com/atom/find-and-replace/pull/572. There were a couple issues:
* The icon was only shown when the find view was open
* The icon could not be centered vertically over the editor in CSS because it was a child of the find view
* The icon was centered horizontally over the fnr panel, not the editor, so it didnt make sense with splits
* The colors didnt work well with some theme combinations
Looks like this now:
cc @mrodalgaard
> Fix up wrap around icon

- lib/find-view.coffee
- spec/find-view-spec.coffee
This is a proposal to fix #496.
The problem
---
Toggling the option buttons will jump you away from a selection that already matched the new settings.
The previous behavior
---
Always jump to the next match after the cursor whenever a find option is toggled.
The new behavior
---
Only jump to the next match **if none of the existing selections match** the pattern.  Inversely, **if any of the existing selections match** the pattern, it will not jump you to the next match.
Alternatives
---
I also considered and decided against these possible behaviors:
- Jump to the next match **if any of the existing selections don't match** the pattern.  Inversely, do not jump to the next match **if all of the existing selections match** the pattern.
- When a find option is toggled, destroy any selections …
> :bug: Fix #496 - Option buttons shouldn't move away from valid match.

- lib/buffer-search.coffee
- lib/find.coffee
- package.json
- spec/buffer-search-spec.coffee
This PR adds a new `find-and-replace@0.0.1` service that exposes a single method `resultsMarkerLayerForTextEditor`. Give it a `TextEditor`, and it will return a marker layer used to store the search results for that editor. It returns null in versions of Atom prior to 1.3.0.
This should make it straightforward to fix packages that relied on finding find-and-replace markers in the default marker layer by simply wrapping introducing a service call to retrieve the appropriate layer for that editor before calling `findMarkers`. Everything else should remain the same.
I'm planning to hotfix this into beta tomorrow morning so it goes out with the introduction of layers.
Refs atom/atom#9208
/cc @abe33 @lee-dohm
> Add service to access result marker layer

- lib/find-view.coffee
- spec/find-view-spec.coffee
I think @nathansobo, @kevinsawicki and I have all found it annoying that the icon shows up even if the editor does not scroll.
> Only show search wrap icon when scroll position changed

- lib/project/match-view.coffee
- lib/project/results-view.coffee
- spec/results-view-spec.coffee
Single click on search result opens file in pending state. Double click opens file in regular non-pending state.
Corresponds to [atom/atom/pull/10178](https://github.com/atom/atom/pull/10178)
Addresses [atom/atom/issues/9165](https://github.com/atom/atom/issues/9165)
Specs included.
> Open file in pending state on single click

- lib/buffer-search.coffee
- spec/find-view-spec.coffee
This will catch `RegExp too big` errors and properly display them in the find box instead of a) displaying a uncaught exception, b) breaking tab switching, and c) (sometimes) preventing the find box from being usable.
TODO:
Fixes #510
Fixes #532
> Catch scanInBufferRange errors

- lib/find-view.coffee
- spec/find-view-spec.coffee
> Prevent 'getSelectedBufferRanges' uncaught exception

- lib/find.coffee
- lib/project-find-view.coffee
This PR adds the following change: when toggling the project-find panel via the ``project-find:toggle`` command from an invisible state, the search input is focused after the panel becomes visible. This is preferable for the following reasons:
* This exact behaviour is the default for the ``find-and-replace:toggle`` command. Enabling the same behaviour for ``project-find:toggle`` makes find-and-replace more consistent from a UX perspective.
* Some people prefer to use toggling instead of showing and dismissing via ``Esc`` and create according key bindings in their ``keymap.cson``. In such cases it's convenient to also focus the search input.
> Focus project-find search input upon toggle

- lib/find-view.coffee
- lib/find.coffee
The wrap-around icon added in #572 is a nice touch, but it might be (slightly) distracting to some users... I've added an option to control the visibility of the visual cue. It's enabled by default; turning it off will hide the overlay.
> Add package option to disable search-wrap icon

- lib/find.coffee
- lib/history.coffee
- menus/find-and-replace.cson
- package.json
- spec/find-view-spec.coffee
Sometimes I search and replace sensitive info and I don't want to leave it laying around on the system. I added a menu item to allow a user to clear the find/replace history data.
> Add menu command to clear find/replace history.

- lib/project/result-view.coffee
- lib/project/results-view.coffee
`confirm` from `ResultView` returns a boolean, so `editorPromise?.then` fails with an exception. This (1) fixes the issue in `ResultView`, and (2) ensures that the thing we get back from `confirm` is actually promise-like by checking for the existence of a `then` method.
/cc @kuychaco
> Fix exception when double-clicking file name from results view

- lib/buffer-search.coffee
This allows us to avoid using custom properties when marking ranges, which is going to be deprecated with the DisplayLayer refactoring. This should be a safe change now that MarkerLayers have been released on both Atom stable and beta.
/cc: @nathansobo
> Remove backwards-compatible change now that MarkerLayers shipped

- lib/buffer-search.coffee
This fixes a leftover deprecation I missed on #697. It should work just fine also on atom stable/beta.
> Fix future DisplayLayer deprecation by setting `maintainHistory` on the MarkerLayer

- styles/find-and-replace.less
This patch removed needless prefixes for `flex`. Chromium supports clear flex since version 29
> Remove needless prefixes for flex

- README.md
- keymaps/find-and-replace.cson
- lib/find.coffee
- lib/project-find-view.coffee
- package.json
This request is to add finding the selected word in the parent directory functionality and mapping to 'alt-a' key.
Finding in parent directory is frequently used when reading souce code.
And using hot key is more convenient than using the 'Search In Directory' context menu command.
> Add find in parent directory functionality

- spec/find-view-spec.coffee
> Disable autoHeight when explicitly setting editors' height in specs

- lib/default-file-icons.coffee
- lib/file-icons.coffee
- lib/find.coffee
- lib/project/result-view.coffee
- package.json
- spec/results-view-spec.coffee
[Same affair as before](https://github.com/atom/fuzzy-finder/pull/211). Hooks the `find-and-replace` package up to the icon-service, allowing packages to customise the file-icons that're displayed in project search results.
> Add logic to consume file-icons service

- lib/find-view.coffee
There is currently a very annoying bug in atom where if you are quick to search, it will override the search with the previous value. See https://github.com/atom/find-and-replace/issues/758 for the bug report and repro steps.
Looking at the blame, it looks like the behavior to replace the text was there since the very early days but in 2014, a check was added to make sure that it doesn't override it if the text is the same as it would make the cursor jump ( https://github.com/atom/find-and-replace/issues/121 ).
I don't understand why when the result of a search comes back, you want to modify the input text. I do think this is a bug and the behavior should be to just leave the text as is and when that new text is finished searching it'll update the search results. So, this removes the …
> Fix cmd-c cmd-f quick sequence from altering the text

- styles/find-and-replace.less
We are in the process of removing the shadow DOM boundary from `atom-text-editor` elements. This pull request upgrades existing selectors so that they:
* Stop using `:host`.
* Stop using `atom-text-editor::shadow`.
* Prepend syntax class names with `syntax--`.
/cc: @simurai
> Stop using shadow DOM selectors

- lib/find.coffee
There's a long standing issue where cmd-e shows the find panel where it shouldn't: https://github.com/atom/find-and-replace/issues/332
This pull request prevents the find panel from showing.
Test Plan:
1) Click on `new`
2) Press `cmd-e`, note that there is no visual feedback
3) Press `cmd-g` multiple times to go through occurrences
See the behavior in Sublime:
In Atom with this pull request:
It even works the same way in Chrome!
> Don't show find panel when doing cmd-e

- lib/project/results-pane.coffee
- lib/project/results-view.coffee
- spec/results-view-spec.coffee
- styles/find-and-replace.less
I often find myself scrolling a big list of results just to find a specific file. Following the `styleguide` approach. I made this small UI change.
> Add feature collapse and expand results

- lib/buffer-search.coffee
- spec/buffer-search-spec.coffee
We were using a `Patch` from *two* implementations ago. It's not needed anymore.
> Stop using old patch

- lib/buffer-search.js
- spec/buffer-search-spec.coffee
- spec/find-view-spec.coffee
When https://github.com/atom/text-buffer/pull/193 lands, we will no longer track the ranges of destroyed markers. This requires a minor tweak in this package to query markers' ranges *before* destroying them.
/cc @nathansobo I could imagine community package authors having to make similar changes 😬
> Don't rely on destroyed markers preserving their ranges

- lib/find.coffee
- lib/project-find-view.coffee
- lib/project/match-view.coffee
- package.json
- spec/project-find-view-spec.coffee
- spec/results-view-spec.coffee
It would be great to be able to open project-find results in a downward pane as per #585, so I'm attempting to update and address the comments on #597 by @bencolon. Changes from that PR:
- Resolved the conflict in one of the spec files
- Now using a none/down/right schema to match atom/markdown-preview#368 as per review comment by @acontreras89 (allows for future support of left/up if desired)
- A fix for a problem with single-click pending mode that the specs were catching
> Results pane direction option (#585, #597)

- lib/find.coffee
- lib/project-find-view.coffee
- lib/project/match-view.coffee
- package.json
- spec/project-find-view-spec.coffee
- spec/results-view-spec.coffee
Convert the `openProjectFindResultsInRightPane` option to a more flexible `openProjectFindResultsInANewPane` option to open results in a new right OR bottom pane.
This update requires an Atom engine >=1.2.0 because it's using a workspace API [update](https://github.com/atom/atom/commit/1b0d72b232234cbcaf0faaf3a66c29047e594696) released from 1.2.x
About migrating the old option to the new one, I'm not sure the four lines I've added at the top of `lib/find.coffee` is the right way. It works but feel free to suggest me a better solution if needed.
Fix #585
> Add an option to open results in a right or a bottom pane

- lib/find-view.coffee
- menus/find-and-replace.cson
- package.json
- styles/find-and-replace.less
These changes address issue [#568](https://github.com/atom/find-and-replace/issues/568) by adding a "Find All" button to the file-view find and replace as well as to the Find menu.
> Introduce "Find All" button

- lib/find-view.coffee
- lib/project-find-view.coffee
- spec/find-view-spec.coffee
- styles/find-and-replace.less
This moves the option buttons into the header.
Also the "Find in project" options got are moved to stay consistent:
Note: The buttons are a bit large, but that's an issue with the One themes.
Keeps the options button grouped together in a row and doesn't give the impression that the bottom two are part of "replace".
- The header text starts wrapping earlier
- Initially will mess with people's muscle/visual memory.
This is a follow up to: https://github.com/atom/find-and-replace/pull/785#issuecomment-270996274
And an alternative to: https://github.com/atom/find-and-replace/pull/839
> Move options into the header

- lib/project/results-model.coffee
- spec/results-model-spec.coffee
Fixes #841.
As a result of https://github.com/atom/text-buffer/pull/193, buffers are now emptied out after they get destroyed, although they can still be queried without throwing exceptions. This package was mistakenly assuming that queries to destroyed buffers would return valid answers. In particular, an error was being thrown after doing a workspace-wide search, opening a search result, then closing it and copying the current `ResultsView` into a new pane (as mentioned in https://github.com/atom/find-and-replace/issues/841#issuecomment-274886326).
This problem occurred because `ResultsModel` was storing references to the match objects created via `TextBuffer.prototype.scan`: these objects (e.g. https://github.com/atom/text-buffer/blob/master/src/match-iterator.coffee#L4) contain lazily …
> Fix copying `ResultsView` into a new pane after opening and closing a search result

- lib/project/results-view.js
- spec/results-view-spec.js
This fixes a regression introduced in https://github.com/atom/find-and-replace/pull/838.
> Fix project replacements that use captures

- spec/find-view-spec.js
Just a couple tweaks so we can get this building on https://github.com/atom/atom/pull/13880. It should still build green against stable.
> Make tests compatible with new editor rendering

- lib/find-view.js
- lib/project-find-view.js
- styles/find-and-replace.less
Add a close button to the Find in Current Buffer panel and the Find in Project panel
Could be on the left
People with a 2016 Macbook pro can finally close the find-and-replace panel
Takes up screen real estate. Might need to consider a setting to enable/disable it.
#164
#204
#219
#347
#683
> add close button

- lib/find-view.js
- lib/find.coffee
- lib/project-find-view.js
- lib/project/results-model.coffee
- spec/find-view-spec.js
- spec/project-find-view-spec.js
- spec/results-model-spec.js
- spec/results-view-spec.js
This restores the pre-docks behavior and fixes #901
/cc @iolsen @lee-dohm
> Use workspace center for all pane item interactions

- lib/find-options.coffee
- lib/find-view.js
- lib/project/match-view.js
- lib/project/result-view.js
- lib/project/results-pane.js
- lib/project/results-view.js
- spec/results-view-spec.js
- styles/find-and-replace.less
The package has config settings for the number of context lines before and above each matched line. The default values are zero in order to not change previous behavior (and show no context by default). When any of these values is set to non-zero the view always shows the context lines.
This patch adds a button to the results pane to toggle between showing and hiding the context lines. If the config values for the context lines are both zero the button is not shown since it wouldn't do anything.
The user can toggle the context lines without the need to change the package settings and redo the query.
Currently there is no option to hide the context lines by default (when non-zero values are in the config). Maybe the latest state can be made persistent to use it for the next search result? …
> Toggle context lines

- lib/project/results-view.js
- package.json
The patch increases the default values of queried context lines.
**Update:** this identified a regression in the scrolling behavior which has been fixed in the second commit. More details in the next comment.
Every user would need to change the settings to benefit from the new functionality to show context lines around search results. With the default of zero non of these UI improvements implemented in #908 are available.
While the queried context lines are not shown by default the increased default values will make the UI elements to show context lines around search results on demand available to all users.
Slightly more memory usage for search results since they store the additionally queried context lines.
None afaik.
> increase default number of queries context lines

- lib/project/match-view.js
- spec/results-view-spec.js
- styles/find-and-replace.less
Currently each line shown in the result view has the leading spaces stripped. For some context / languages whitespace is critical. Especially when also showing context line the relative indentation can be very important.
This patch keep the leading whitespace and makes sure it is rendered correctly (not collapsing multiple spaces into a single visual space).
If the new behavior is not considered desired an option could be introduced to toggle the two possible behaviors (hide leading whitespace vs. showing them).
Context awareness.
The additional indentation will move the text of the line further to the right.
None, as far as I know.
> keep leading whitespace

- lib/project/results-model.coffee
- lib/project/results-view.js
- spec/results-view-spec.js
Fixes #909.
The result view stores the result and match index to identify the currently selected result and match within the result. When results are being removed from the model (as described in #909) (or added) the view doesn't update those indices and therefore might either reference the "wrong" result/match or even an invalid one.
This patch ensures that the view updates those indices when the model changes.
All the internal calculations operating on the result and match index work on the assumption that the indices are valid. A lot of code parts would need to be updated to add additional checks before using and changing the indices. Therefore I think the proposed patch to ensure that indices stay valid is the better approach.
The result and match indices stay valid with allows the …
> keep selection indices valid when adding / removing results

- lib/project-find-view.js
- lib/project/results-model.coffee
- spec/project-find-view-spec.js
Fixes #612 by closing the project search panel only when a search has actually completed, _not_ including the handler for clearing replacement state (which is triggered each time a character is entered in the replace field).
> Keep search panel open when typing in replacement field

- styles/find-and-replace.less
This styles the context lines a bit more:
Before | After
--- | ---
It would be nice if the context lines and line numbers would also have the same font family as the `.match-line`. It could be done by inlining the font-family to a parent element, maybe `ol.matches`? But I couldn't figure out how. 😞  
It should make it easier to see where new matches start.
Context lines are now more subtle and might not have enough contrast. Also, depends on the theme used.
Continues from #908
/cc @dirk-thomas
> Context lines styling

- lib/find-view.js
- lib/project/results-view.js
- spec/find-view-spec.js
If the match is folded, unfold it when it's searched for.
None.
Being able to actually see what you were searching for instead of having to manually unfold.
None.
Fixes #930
> Unfold on find

- lib/find-options.coffee
- spec/project-find-view-spec.js
The multiline flag changes `^` and `$` to line-based rather than file-based.  
None.
Replacing with `^` and `$` will work as expected.
None.
Fixes #622
Refs atom/atom#15224
I believe the build will fail since atom/atom#15224 is only on Atom 1.21.0.
> Use multiline flag when replacing

- lib/project/results-model.coffee
- spec/project-find-view-spec.js
- spec/results-model-spec.js
- spec/results-view-spec.js
* Remove outdated 1.17 version checks
* Use `temp.track()` and `temp.mkdirSync()` rather than `os.tmpdir()`
* Clean up some ugly watcher code from 2013
> Spec cleanup

- lib/find.coffee
- package.json
This pull request is a continuation of #710 after addressing comments by @as-cii.
> This PR enables autocompletion in the find editor by:
> - Registering the find editor so it's observable by autocomplete-plus
> - Adding a corresponding CSS selector to the default provider so it knows to provide completions for that editor.
Depends on atom/autocomplete-plus#864.
This will provide autocompletion when searching.
Fixes atom/find-and-replace#92.
> Enable autocompletion in the find editor

- keymaps/find-and-replace.cson
The keymap for `project-find:toggle-case-option` was wrong and pointed to the `find-and-replace:toggle-case-option` instead.
Bug fix. The keymap will now work.
> Fix project-find:toggle-case-option keymap on Windows & Linux

- lib/buffer-search.js
- lib/find-options.coffee
- lib/find-view.js
- lib/find.coffee
- spec/buffer-search-spec.js
Previously, we were only researching when the find options or the find text changed.  This meant that when "Only in selection" was enabled and the selection was changed, the aforementioned prerequisites were not met and so cached results were returned rather than searching in the new selection.
To make "Only in selection" searching work correctly, `findOptions.set` now returns the changed params so that `BufferSearch` doesn't have to rely on an `onDidChange` callback.  We can then immediately determine whether or not to execute another search.
None.
In …
>  Re-search when selection changes and "Only in selection" is set

- lib/select-next.coffee
- spec/select-next-spec.js
With this pull request, the find and replace package will start honoring the reversed orientation of previous selections when the user dispatches the following commands:
* `find-and-replace:select-next`
* `find-and-replace:select-all`
* `find-and-replace:select-skip`
None.
Selections will look consistent when created using the commands above.
Unclear.
Fixes #928
> Honor reversed orientation of previous selections when "selecting next"

- lib/buffer-search.js
- spec/buffer-search-spec.js
Refs https://github.com/atom/text-buffer/pull/289
Refs https://github.com/atom/superstring/pull/50
This was just a quick win I wanted to do after I had to reimplement `TextBuffer.scanInRange` in order to fix https://github.com/atom/atom/issues/15325.
We should still restructure this code at some point (maybe adding an async variant of `findAndMarkAllInRange`), but this small code change already makes a pretty big difference. Searching the letter 'e' in a big file like jquery used to take about **285ms** on my machine, and now it takes about **65ms**. A big part of this cost is now instantiating `Marker` objects. Finding and marking the ranges takes about 39ms.
/cc @nathansobo
> Optimize buffer search using findAndMarkAllInRangeSync

- lib/project/list-view.js
- styles/find-and-replace.less
This PR makes sure there is no horizontal scrollbar so that the last result can be clicked.
The problem is that these `<div>`s have `width: 100%`.
And the parent `list-tree` has some padding. But the `width: 100%` of the children doesn't take the padding into account and so they extend to much, causing the horizontal scrollbar to appear.
**Fix 1**: Move the padding from the parent `list-tree` into the children. Now the `width: 100%` matches the parent's width.
**Fix 2**: Adds some bottom padding so there is always some space reserved for the horizontal scrollbar. I think it still looks ok.
We could also make these `<div>`s not take up `100%` width, but stretch them with `left: 0 right: 0`.
Last result is clickable.
None
Closes #943
> Fix last result not clickable

- lib/project/results-pane.js
- spec/results-view-spec.js
- styles/find-and-replace.less
Personally I'd like the "Collapse All" and "Expand All" just be a single toggle button. And also only have a single show/hide more lines number stepper that changes above and below.
Allows the search results be in a narrow place.
None.
This is a follow up to #992.
> Responsive results header

- spec/results-view-spec.js
The work in atom/atom#17021 causes this spec to fail:
```
ResultsView
opening results
it opens the file containing the result in a non-pending state when the search result is double-clicked
Expected <TextEditor 1552> to be null.
Error: Expected <TextEditor 1552> to be null.
at /Users/distiller/atom/node_modules/find-and-replace/spec/results-view-spec.js:417:75
at Generator.next (<anonymous>)
at step (/Users/distiller/atom/node_modules/find-and-replace/spec/results-view-spec.js:1:428)
at <anonymous>
```
This is because `await paneItemOpening()` now resolves after the single-click's `Workspace.open()` call resolves, but before the double-click's does to activate the item as non-pending. By explicitly waiting for a non-pending item to appear before resolving the helper we can make this more …
> Explicitly wait for a non-pending item

- lib/buffer-search.js
- lib/find-view.js
- spec/find-view-spec.js
When toggling "only in selection," only select the first marker after the cursor if there was no actual selection. Otherwise, when `this.search()` is called immediately before a replaceAll operation, the selection was replaced by the first marker and only the first marker is actually replaced.
Fixes #1005.
> Don't modify selection when toggling "only in selection"

- lib/project/results-view.js
- spec/results-view-spec.js
When searching across projects, if some items are collapsed in the search results view and new results are added, the collapsed items do not stay in sync with the results. Instead, collapsed items are "sliding" up and down as results are added/removed. This is due to the collapsed state being represented by an array of booleans that does not get updated when search results change. This commit introduces a fix to that issue by making sure that we update the aforementioned array as needed.
An alternative to this design would have been to store the collapsed state directly on the element representing a "matched file" but it would entail a pretty big refactoring of the code which I don't feel I am familiar enough to start modifying in such length.
Whenever search results are updated, if some …
> Keep collapsed items in sync with search results

- lib/find-view.js
This resolves the null reference error reported in #1012 by simply checking if an active editor exists in the workspace. The bug was introduced in #1007, specifically [this change](https://github.com/atom/find-and-replace/pull/1007/files#diff-031d2cf6de79608fdbf0fde30f0fc2f8R701).
Note that I haven't found a simple way of implementing a regression test for this. I tried spying on `atom.onDidThrowError`, the notification system, etc. They work OK-ish when the test fails prior to applying this PR since I was using `waitsFor`. Although, that means once the fix has been applied, the `waitsFor` block in the regression test waits until timeout, which seems a bit unfortunate. Any proposals for writing a good regression test is very much appreciated.
No other alternatives were considered.
Fixes …
> Check if an active editor exists when toggling "Only in Selection"

- keymaps/find-and-replace.cson
Adds keymaps when pressing "home" and "end" in project search, that trigger `ResultsView.moveToTop` and `ResultsView.moveToBottom` respectively.
The code for these methods already existed, but it wasn't linked to any keymaps, and the only way to trigger them was to e.g. write "Core: Move To Top" in the command panel.
Being able to quickly select the first/last result in project search using the keyboard.
No alternate design, no likely drawback, I don't think any issue was made on the subject.
> Add keymaps for home and end to project search

- menus/find-and-replace.cson
Fixes #1032.
---
\#1032 reports that the [selector changes](https://github.com/atom/find-and-replace/commit/befebde9a6830e126a156cb33b5a8b99a77191d6) in #1002 cause find-and-replace's "Copy Path" menu item to unintentionally appear in tree-view's context menu. This pull request applies a more specific CSS selector to the "Copy Path" menu item, ensuring that it appears where we want it in the find-and-replace context menu, but not where we don't want it in the tree-view context menu.
The changes in #1002 were first released in find-and-replace v0.215.10. I checked out v0.215.9 to compare the behavior prior to #1002, the behavior in v0.215.10 (after #1002), and the behavior resulting from the changes in this pull request:
| version | tree-view context menu | search results context menu for …
> Don't show find-and-replace "Copy Path" item in tree-view context menu

- lib/project-find-view.js
When the `ctrl+shft+f` is pressed the search and replace feature opens. The screenshot below shows the field that I'm proposing to edit (3rd field that allows users to specify what path they prefer to search)
Currently the placeholder for the 3rd field reads as follows:
> File/directory pattern. eg. `src` to search in the "src" directory or `*.js` to search all JavaScript files
I'm proposing for the placeholder text to read as follows: 
> File/directory pattern. eg. `src` to search in the "src" directory; `*.js` to search all JavaScript files; `!*.png` to exclude all PNG files
_Note:_ The screenshot's function is to show where I mean to replace the placeholder text. I tried to actually manipulate the UI in the js console but atom reported an error so apologies for not demoing what it …
> Add extra placeholder text on how to exclude files in the find-and-replace 3rd field

- lib/buffer-search.js
Quick follow-up from #966, to definitively make clear that the existence of a buffer does not matter; rather, it is the text editor itself that counts.
There is no change in functionality, as `editor.onDidStopChanging` [directly calls the TextBuffer version](https://github.com/atom/atom/blob/62690f7783da86e6975398bca758563de99b4e2e/src/text-editor.js#L685).
> Use editor.onDidStopChanging, not editor.getBuffer().onDidStopChanging

- menus/find-and-replace.cson
There is some inconsistency between us and [tree-view](https://github.com/atom/tree-view/blob/master/menus/tree-view.cson) in choosing the term "folder" or "directory" in the context menu. The "Search in Directory" context menu item is shown alongside tree-view's "New Folder" item. This PR changes our item to "Search in Folder" for consistency.
Alternatively, we could have tree-view change its "Folder" items to say "Directory". But they have several, and we have one.
It makes the resulting context menu more pleasing to read.
It looks like most of the internal code uses the word "directory", so the user-visible label will not match the internals, which is always unfortunate.
None.
> Change "Search in Directory" to "Search in Folder"

- styles/find-and-replace.less
Remove the hardcoded font names, so that the package use Atom’s font.
Before (setting the Editor font to Inconsolata):
After:
Expose the font used for file names as a configuration option, but I fail to find a compelling use case.
Less code, uniform look, don’t need to change several fonts.
Can’t use another font for file names in search results.
Fix #1057
> Remove hardcoded fonts so that search view always use Atom’s font

- lib/find.coffee
- spec/find-spec.js
- spec/item/embedded-editor-item.js
- spec/item/unrecognized-item.js
In atom/github, we open several pane items that _embed_ TextEditor elements, but are not TextEditors themselves: ChangedFileItems for single file diffs (stage and unchanged), CommitPreviewItems for commit previews, and the "Files Changed" tab within the pull request detail item. <kbd>Cmd-F</kbd> doesn't search them, which is inconvenient, because especially the last two can be large.
To accommodate them, and any other packages that created pane items with internal TextEditors, I'm allowing pane items to implement a `getEmbeddedTextEditor()` method. If …
> Find within TextEditors within non-editor pane items

- lib/find.coffee
- spec/find-spec.js
- spec/item/deferred-editor-item.js
This is a follow-on enhancement to #1068. If the active pane item implements `observeEmbeddedTextEditor`, the find model will track changes to the embedded TextEditor after the pane item activation completes.
_N/A_
atom/github will be able to use this API with React refs, which aren't available synchronously on item activation (oops).
_N/A_
_N/A_
> Understand observeEmbeddedTextEditor to follow embedded TextEditor changes

- lib/find-options.coffee
- lib/find-view.js
- lib/project-find-view.js
- spec/find-view-spec.js
The find and replace package was causing some issues with the cursor when hiding and showing the search panel under some circumstances. I could find two scenarios where this was happening:
* **Scenario 1**: When searching for an existing text but not selecting it from the document (by not pressing `Enter` after searching). This is the scenario described in https://github.com/atom/find-and-replace/issues/1067
* **Scenario 2**: When searching for a non-existing text and then hiding and showing the search panel.
The issues comes from the fact that on every …
> Fix editing the search input when toggling the search pane

- docs/events.md
- lib/find.coffee
- lib/project/results-model.js
- lib/reporter-proxy.js
- package-lock.json
- package.json
- spec/results-model-spec.js
This PR makes use of the `atom/metrics` package to be able to log the time it takes to search all results on a project by the find and replace package.
* **eventType**: `find-and-replace-v1`
* **metadata**
| field | value |
|-------|-------|
| `ec` | `time-to-search`
| `ev` | Number of found results
Sample payload:
```json
{
"eventType": "find-and-replace-v1",
"durationInMilliseconds": 321,
"metadata": {
"ec": "time-to-search",
"ev": 4,
"cd2": "x64",
"cd3": "x64",
"cm1": 180,
"cm2": 83,
"sr": "1680x1050",
"vp": "1680x591",
"aiid": "dev"
},
"date": "2019-05-08T09:59:11.621Z"
}
```
N/A
More information about the performance of the find and replace package.
N/A
> Add metrics logging for time to search in project

- lib/project-find-view.js
- lib/project/results-model.js
This PR tweaks the logic of the method that handles results from the search provider to be able to support results that span across multiple lines.
The current default scanner ([`scandal`](https://github.com/atom/scandal)) does not support multiline regexps, so up until now it was rare to get a search result that contained multiple lines, this is why the current UI does not handle them well.
Still, currently there's one situation where multi-line results are shown, which causes a very broken results view ([more info](https://github.com/atom/find-and-replace/issues/1084)), so this PR aims to fix it.
This PR also paves out the support for [adding `ripgrep` as backend for the searches](https://github.com/atom/find-and-replace/issues/1075), since `ripgrep` can return multi-line results (this …
> Handle multiline results on the find and replace UI

- package-lock.json
This includes:
* [A fix for a deprecation message on electron v3](https://github.com/atom/fs-plus/pull/46) in `fs-plus`.
---
- *List of changes between `fs-plus@3.0.2` and `fs-plus@3.1.1`: https://github.com/atom/fs-plus/compare/v3.0.2...v3.1.1*
> ⬆️ fs-plus@3.1.1

- lib/buffer-search.js
- spec/buffer-search-spec.js
Fixes #1010
Previously, the "Only In Selection" option only supported the *most recently created* selection rather than all selections. This led to particularly bad results when clicking "Find All" and then "Replace All", because "Find All" would select all of the results, creating multiple selections. Then the search markers would be re-created, but only for the last of the selections. When you then clicked "Replace All", only the last of the selected original results would be replaced due to this being the only marker. In this PR, we now loop over all selections when populating the search markers.
In this PR, I'm looping over the selected ranges within the find and replace package and calling `findAndMarkAllInRangeSync` for each range. This will generate a call into the C++ buffer …
> Support multiple selections when "Only In Selection" option is enabled

- spec/results-view-spec.js
Refs https://github.com/atom/atom/issues/19480
This pull request is an attempt at fixing the flaky tests described in the above issue. Such tests were failing in the following way:
```
ResultsView
copying path with find-and-replace:copy-path
it ResultsView copying path with find-and-replace:copy-path copies the selected file path to clipboard
timeout: timed out after 60000 msec waiting for spec promise to resolve
it ResultsView copying path with find-and-replace:copy-path copies the selected file path to the clipboard when there are multiple project folders
timeout: timed out after 60000 msec waiting for spec promise to resolve
```
After analyzing those two code paths, it seems like the so-called `heightInvalidationPromise` may be what the tests get stuck on every now and then on CI. That …
> Try fixing flaky tests in results-view-spec.js

- lib/project/results-model.js
- spec/results-view-spec.js
Fixes https://github.com/atom/atom/issues/19480
Previously, all tests on the `ResultsView` actually ran a real search against the file system to populate their results. We're seeing intermittent failures in a few tests, so I decided to eliminate the async behavior by constructing a `ResultsView` directly with a model and then populating some fake results on the model. This makes the test synchronous and should hopefully eliminate the flakiness.
> Construct ResultsView directly to fix some flaky tests

- lib/project/list-view.js
- lib/project/results-view.js
- package-lock.json
- package.json
- spec/project-find-view-spec.js
- spec/results-view-spec.js
:pear:'d with @as-cii 
Fixes https://github.com/atom/atom/issues/19554
In investigating https://github.com/atom/atom/issues/19554, we discovered that every single test that was awaiting the `heightInvalidationPromise` on its view still passes if we *don't* await that promise. Since we're concerned that these `await`s are the source of timeouts like the one in the linked issue, we decided to completely remove that logic from all tests.
We also took the opportunity to replace `element-resize-detector` with the native `ResizeObserver` API which was introduced after the code in this package was written.
Hopefully this addresses all of the remaining flakiness in our tests for this package.
> Overhaul height invalidation

- lib/project/results-model.js
- package.json
Added option to enable `pcre2` ripgrep regex engine, as discussed [in here](https://github.com/atom/find-and-replace/pull/1086#issuecomment-502605862).
**NOTE:** I haven't written any specs because I'm not sure what steps to take. Should I wrap all the specs in additional loop, same as [prev PR has done with ripgrep support](https://github.com/atom/find-and-replace/pull/1086/files#diff-3529658c67b9493659c04f7644950802R12)?
**NOTE:** cannot build Atom ATM so haven't tested the changes locally.
Allows additional regex features such as lookbehind.
Enabling PCRE2 potentially incurs performance penalty, as explained on [ripgrep's wiki](https://github.com/BurntSushi/ripgrep/blob/7b3fe6b3251a18d2b8d3efe7ee6a85c9e9e4e565/FAQ.md#why-does-ripgrep-get-slower-when-i-enable-pcre2-regexes), thus this …
> Add pcre2 ripgrep option

- lib/buffer-search.js
- lib/find-view.js
- spec/find-view-spec.js
- Checks for the presence of an editor before trying to search text.
- Make find and find all buttons disabled when their feature is not available and add an helpful tooltip on them.
It is implement in `buffer-search.js` because filters need to be updated, and stopping the search in `find-view.js` would prevent that.
The fact that now the buttons are disabled and provide a hint of why it is disabled will help people understand why the find/find all feature is unavailable here.
I can’t see any.
Fix #998 
---
I think these changes need unit tests but I find it more difficult to find what should go where and how to implement these tests properly, so any help to get started is appreciated.
Also during my work, I found that I was able make filters unmodifiable (i.e. clicking filters did …
> Don’t crash when using find view in tab that’s not an editor

- lib/find.coffee
- lib/project-find-view.js
- lib/project/results-pane.js
- spec/project-find-view-spec.js
Every project search, overrides last search's results. This PR adds button to results tab, that when clicked, saves that tab, so it won't be overwritten by next search. Next search will open results in new tab (that can be overwritten, unless button in that one is clicked). After clicking button gets disabled
Main focus is to have multiple results open at the same time. Other approach was to put this button, but it was easy to lose track of what tabs would stay open, and what overwritten.
Easier code navigation
https://github.com/atom/find-and-replace/issues/360
> Add option to save search resulst from being overwrittenby next search

- spec/setup-spec.js
Reduces flaky test failures on the main Atom repo CI. The summary is that an uncaught exception is triggering dev tools, which breaks tests. See https://github.com/atom/atom/pull/21335 for more.
Fixing the root of the problem. But that's a lot more difficult, seeing as the cause hasn't been completely determined yet. Investigations are welcome! 
Reduced false CI failures on main repo PRs
This is only masking the deeper issue, so isn't a fix and should not be treated as such.
None. It does not completely resolve any issues.
> Add devtools catch

- lib/buffer-search.js
- lib/project/util.coffee
- package.json
- spec/buffer-search-spec.js
This PR adds a `preserveCaseOnReplace` option (off by default) which keeps the replaced text case. For exemple, when replacing `test` with `case`:
`test Test TEST` will be replaced with: `case Case CASE`.
This is made by swapping the replacement right before putting it in the buffer in `buffer-search.js`. The `preserveCase` algorithm is trivial and defined in `project/util.coffee`.
**This only works in buffer search. The project replace is done in atom core and should be addressed in a separate ticket.**
One could have added a button for this option, but a plugin configuration was chosen since it concerns only replacing (not searching) and it might not be toggled very often.
Huge benefits arise when replacing variables name that are in different case, for instance replacing in one pass …
> Add preserve case option for buffer replace. References #165.

- lib/project/results-view.js
- menus/find-and-replace.cson
- spec/results-view-spec.js
Added two context-menu options to right clicking on the paths of search results, "Open in New Tab" ~~and "Open in New Window".~~
Can also open new tabs on specific line matches, and already opened tabs will becomes focused after subsequent open attempts:
~~Note: Open in New Window not implemented for specific line matches as this does not appear to be easily accomplished within the current API.~~
Includes tests to guarantee that the context menu commands call the
correct functions with the intended parameters, as well as ensure that
right-clicks have no …
> Added "Open in New Tab" and "Open in New Window" right-click context menu options

- lib/project/results-view.js
Enables atom to focus on a file with matched results if the file is open
in a different pane from the search results
Resolves: #1058
> Add searchAllPanes option
