coffeelint.json, lib/escape-helper.coffee, lib/find-model.coffee, lib/find-view.coffee, lib/find.coffee, lib/history.coffee, lib/project-find-view.coffee, lib/project/result-view.coffee, lib/project/results-model.coffee, lib/project/results-view.coffee, lib/select-next.coffee, package.json, spec/results-view-spec.coffee
Refs atom/atom#6230, atom/atom#5982
=> Add coffeelint support

coffeelint.json, lib/find-model.coffee, lib/select-next.coffee, package.json, spec/find-view-spec.coffee, spec/project-find-view-spec.coffee
Refs https://github.com/atom/atom/issues/5982
=> Update coffeelint support

lib/buffer-search.coffee, spec/buffer-search-spec.coffee
* Re-scan touched regions if changes were completely undone
* Re-scan past existing markers in case search results were extended
=> Handle edge cases when rescanning parts of buffer

lib/buffer-search.coffee, spec/buffer-search-spec.coffee
=> Avoid observing find-result Markers

lib/buffer-search.coffee
Refs https://github.com/atom/text-buffer/pull/71
=> Don't maintain history of markers

lib/find-view.coffee, spec/find-view-spec.coffee
=> Disable replace buttons when replacement is not possible un buffer find

lib/find-view.coffee, spec/find-view-spec.coffee
=> Set selected text in replace editor on find-and-replace:show-replace

lib/project-find-view.coffee, lib/project/results-model.coffee, spec/project-find-view-spec.coffee
it now says `Searching...` when it's searching, and doesnt clear when results + hitting confirm in the find box.
=> Clean up project find message

spec/find-view-spec.coffee
Refs: atom/atom#8905
/cc: @maxbrunsfeld
=> Fix deprecations

lib/find-view.coffee, spec/find-view-spec.coffee
=> Find previous on shift + click 'find'

lib/find.coffee
As a followup to atom/atom#9096, this adds descriptions for config settings in this package.
=> Add descriptions for config settings

lib/buffer-search.coffee, spec/buffer-search-spec.coffee, spec/find-view-spec.coffee, spec/project-find-view-spec.coffee
Supplants #577
This is backwards compatible with versions of Atom prior to these APIs, but will use them if available for better performance.
=> Use marker layers and layer decorations *if available* for improved performance

lib/project/results-view.coffee, spec/results-view-spec.coffee
Corresponding pane pending item API - https://github.com/atom/atom/pull/10959
Signed-off-by: Michelle Tilley <binarymuse@github.com>
=> Add support for new pane pending item api

lib/project/results-view.coffee, spec/results-view-spec.coffee
=> Keep focus on single click and update to use 1.6stable pending items api

lib/project/results-view.coffee, spec/results-view-spec.coffee
This was a nice idea but felt too unintuitive.
=> Always open search results on single click

lib/buffer-search.coffee, spec/buffer-search-spec.coffee
=> Unescape escape sequence once on replacing buffer using regex

lib/find.coffee, spec/results-view-spec.coffee
Same thing as https://github.com/atom/tree-view/pull/967
Closes https://github.com/atom/find-and-replace/pull/792
=> Remove unnecessary onWillDeactivate method from file-icons service

lib/find-view.coffee, lib/project-find-view.coffee, spec/find-view-spec.coffee
=> Add css class based on if results were returned from a find

lib/buffer-search.coffee, lib/find-view.coffee, spec/find-view-spec.coffee
Addresses https://github.com/atom/find-and-replace/issues/803
=> don't do live search if regex matches empty string

lib/buffer-search.coffee, lib/find-view.coffee, spec/find-view-spec.coffee
Refs #805.
Fixes #809.
/cc: @atom/maintainers and @maxbrunsfeld for 👀
=> Don't live search with invalid regexes

menus/find-and-replace.cson
Fixes https://github.com/atom/find-and-replace/issues/887
=> Fix tree view selector for Search in Directory context menu item

lib/project/match-view.js, lib/project/results-model.coffee, spec/results-model-spec.js, spec/results-view-spec.js
* To be filled out when I get this actually working...
=> Add spec for context lines

lib/find.coffee, package.json
=> Option to enable autocompletion

lib/find.coffee
Fixed #950
Commands should be removed when the package is deactivated.
Fixed #950
=> Fixed #950

spec/async-spec-helpers.js, spec/find-spec.js, spec/find-view-spec.js, spec/project-find-view-spec.js, spec/result-row-spec.js, spec/results-model-spec.js, spec/results-view-spec.js, spec/select-next-spec.js
They are not needed anymore after https://github.com/atom/atom/pull/18917 🎉
=> Remove async test helpers

lib/project-find-view.js, spec/project-find-view-spec.js
Fixes https://github.com/atom/find-and-replace/issues/1129
=> Fix broken replace all function

lib/project-find-view.js, spec/project-find-view-spec.js
Fixes: https://github.com/atom/atom/issues/21622
This PR reverts https://github.com/atom/find-and-replace/pull/1128 in favor of https://github.com/atom/atom/pull/21587
=> FIxes broken find and replace button

CONTRIBUTING.md
in the flight manual
fix #1049 
=> docs(CONTRIBUTING.md): add link to Running Specs

lib/find-view.js
<kbd>Shift</kbd> + <kbd>Replace</kbd> = replace previous
exactly how <kbd>Find</kbd> button works
This is alternative to #1112
can easily replace and select previous.
none
=> shift replace previous
